# Generated by Django 3.2.8 on 2021-10-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictureday',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
