# Generated by Django 3.2.8 on 2021-10-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apod', '0002_pictureday_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictureday',
            old_name='image',
            new_name='image_file',
        ),
        migrations.AddField(
            model_name='pictureday',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
