# Generated by Django 3.2.8 on 2021-10-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apod', '0003_auto_20211017_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictureday',
            name='image_url',
        ),
        migrations.AddField(
            model_name='pictureday',
            name='media_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
