# Generated by Django 3.2.8 on 2021-10-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apod', '0004_auto_20211017_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictureday',
            name='video_url',
            field=models.URLField(default='None'),
        ),
    ]
